### ISSUE TITLE
100% panic in dev chain when try to transfer via `ckb-cli`

### ISSUE THREAD

**Issue by yangby-cryptape** [nervosnetwork/ckb-cli#350] opened 2020-11-11 07:38 UTC
### Version

- `ckb 0.37.0 (3076ff6 2020-10-20) `
- `ckb-cli 0.37.0 (7a9dc90 2020-10-20)`

### Reproduce

- `ckb init -C . --chain dev`
- Add block assembler information.
- `ckb run -C .`
- `ckb miner -C .`
- `rm -rf ${CKB_CLI_HOME}`
- `ckb-cli`
  - `wallet get-capacity --address ${address}`
    ```
    immature: 8038621.3196769 (CKB)
    total: 97258300.3115108 (CKB)
    ```
  - `wallet transfer --to-address ${address} --capacity 100 --tx-fee 0 --privkey-path ${key}`
    ```
    thread 'main' panicked at 'attempt to subtract with overflow', src/subcommands/wallet/mod.rs:361:33
    note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
    ```

### And A Question?

How did you pass your integration tests?
https://github.com/nervosnetwork/ckb-cli/blob/v0.37.0/test/src/spec/wallet.rs#L65-L68

**Comment by TheWaWaR** [comment] 2020-11-11 08:05
Can't reproduce.

**Comment by yangby-cryptape** [comment] 2020-11-11 08:32
After a face-to-face discussion, the reason cause panics are:

- The strategy for collecting cells when calling `transfer`:
  - Try **zero input cell**, if not enough, try one input cell, and so on.
    But since #349, in my laptop, it will always panic, **no matter** if I really have enough cell.
    Because `ckb-cli` always try if use **zero input cell** can transfer, so it always panics.

- `ckb-cli` can't know the cellbase maturity.

**Comment by TheWaWaR** [comment] 2020-11-19 02:28
1. Can't reproduce in my machine and don't receive any report from others
2. After https://github.com/nervosnetwork/ckb-cli/pull/349, it already works on your machine

So, I'm going to close this issue.

**Closed by TheWaWaR** 2020-11-19 02:28 UTC
